### ISSUE TITLE
Unable to align website for Markbot completion

### ISSUE THREAD

**Issue by hovski** [hovski/sections#1]
I tried to adjust the margins for both <div> boxes as well as many attempts at adjusting the margins to shift the <a> tag up. I've gotten the images and text to match pretty close if not perfect, but I can't get the button to match exactly - using the given padding numbers.

Markbot keeps demanding a 13% difference and the best I seem to get is 30%.

@thomasjbradley

**Comment by thomasjbradley** [comment]
I see it’s still the placeholder graphic—it should be replaced with the actual photograph. That might get much closer.

For the margin/padding, on the top and bottom of some elements, could the margin/padding be `0`?
